name: Destroy miserv.io infrastructure
on:
  workflow_dispatch:

jobs:
  destroy_aws_infrastructure:
    name: Destroy the AWS infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.3.6

      - name: Tf init kubernetes
        run: |
          terraform -chdir=./kubernetes init \
          -backend-config="bucket=miservio-terraform-state" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region=eu-west-1"

      - name: tf destroy kubernetes
        run: |
           terraform -chdir=./kubernetes destroy -auto-approve

      - name: Terraform init
        run: |
          terraform init \
          -backend-config="bucket=miservio-terraform-state" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region=eu-west-1"

      - name: Terraform destroy
        run: |
          aws eks update-kubeconfig --region eu-west-1 --name miserv-io-eks-cluster
          terraform destroy -auto-approve
